require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - "config/rubocop/rails.yml"
  - "config/rubocop/rubocop.yml"
  - "config/rubocop/rspec.yml"

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.4
  Exclude:
   - 'db/**/*'
   - 'config/**/*'
   - 'config.ru'
   - 'vendor/**/*'
   - 'bin/**/*'
   - 'Gemfile'
   - 'test/test_helper.rb'
   - 'node_modules/**/*'
   - 'Rakefile'
